;
;	This file was generated by the GEOS Resource Compiler
;
;	DO NOT EDIT! Any changes will be lost!
;
;	Edit proper resource file instead.
;

		.segment "DIRENTRY"

	.byte 131
	.word 0
	.byte "geoLinkEmbed"
	.res  (16 - 12), $a0
	.word 0
	.byte 0
	.byte 6
	.byte 18, 7, 27, 8, 32

	.word 0
	.byte "PRG formatted GEOS file V1.0"

		.segment "FILEINFO"

	.import __VLIR0_START__, __STARTUP_RUN__

	.byte 3, 21, 63 | $80
	.incbin "icon-program.bin", 0, 63
	.byte 131, 6, 0
	.word __VLIR0_START__, __VLIR0_START__ - 1, __STARTUP_RUN__

	.byte "geoLinkEmbed"
	.byte "V1.0"
	.byte 0, 0, 0
	.byte 0

	.byte "ShadowM"
	.byte 0
	.res  (63 - 8)

	.byte "Embeds IP stack and mono font."
	.byte 0

