;
;	This file was generated by the GEOS Resource Compiler
;
;	DO NOT EDIT! Any changes will be lost!
;
;	Edit proper resource file instead.
;

		.segment "DIRENTRY"

	.byte 131
	.word 0
	.byte "geoLink"
	.res  (16 - 7), $a0
	.word 0
	.byte 1
	.byte 6
	.byte 18, 7, 27, 8, 32

	.word 0
	.byte "PRG formatted GEOS file V1.0"

		.segment "FILEINFO"

	.import __VLIR0_START__, __STARTUP_RUN__

	.byte 3, 21, 63 | $80
	.incbin "icon-program.bin", 0, 63
	.byte 131, 6, 1
	.word __VLIR0_START__, __VLIR0_START__ - 1, __STARTUP_RUN__

	.byte "geoLink"
	.res  (12 - 7), $20
	.byte "V1.0"
	.byte 0, 0, 0
	.byte 0

	.byte "ShadowM"
	.byte 0
	.res  (63 - 8)

	.byte "Links GEOS users together over the 'net."
	.byte 0

		.segment "RECORDS"

	.import __VLIR0_START__, __VLIR0_LAST__, __BSS_SIZE__
	.import __VLIR1_START__, __VLIR1_LAST__
	.import __VLIR2_START__, __VLIR2_LAST__
	.import __VLIR3_START__, __VLIR3_LAST__
	.import __VLIR4_START__, __VLIR4_LAST__
	.import __VLIR8_START__, __VLIR8_LAST__
	.import __VLIR9_START__, __VLIR9_LAST__

	.byte .lobyte ((__VLIR0_LAST__ - __VLIR0_START__ - __BSS_SIZE__ - 1) /    254) + 1
	.byte .lobyte ((__VLIR0_LAST__ - __VLIR0_START__ - __BSS_SIZE__ - 1) .MOD 254) + 2
	.byte .lobyte ((__VLIR1_LAST__ - __VLIR1_START__ - 1) /    254) + 1
	.byte .lobyte ((__VLIR1_LAST__ - __VLIR1_START__ - 1) .MOD 254) + 2
	.byte .lobyte ((__VLIR2_LAST__ - __VLIR2_START__ - 1) /    254) + 1
	.byte .lobyte ((__VLIR2_LAST__ - __VLIR2_START__ - 1) .MOD 254) + 2
	.byte .lobyte ((__VLIR3_LAST__ - __VLIR3_START__ - 1) /    254) + 1
	.byte .lobyte ((__VLIR3_LAST__ - __VLIR3_START__ - 1) .MOD 254) + 2
	.byte .lobyte ((__VLIR4_LAST__ - __VLIR4_START__ - 1) /    254) + 1
	.byte .lobyte ((__VLIR4_LAST__ - __VLIR4_START__ - 1) .MOD 254) + 2
	.byte $00
	.byte $FF
	.byte $00
	.byte $FF
	.byte $00
	.byte $FF
	.byte .lobyte ((__VLIR8_LAST__ - __VLIR8_START__ - 1) /    254) + 1
	.byte .lobyte ((__VLIR8_LAST__ - __VLIR8_START__ - 1) .MOD 254) + 2
	.byte .lobyte ((__VLIR9_LAST__ - __VLIR9_START__ - 1) /    254) + 1
	.byte .lobyte ((__VLIR9_LAST__ - __VLIR9_START__ - 1) .MOD 254) + 2

	.export __STACKSIZE__ : absolute = $0200

	.export __OVERLAYSIZE__ : absolute = $2200

	.export __BACKBUFSIZE__ : absolute = $0000

